# Generated by Django 5.2 on 2025-04-12 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_level_subject_userprofile_level_userprofile_subject"),
    ]

    operations = [
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("level", models.IntegerField()),
                (
                    "subject",
                    models.CharField(
                        choices=[
                            ("math", "Math"),
                            ("science", "Science"),
                            ("gk", "General Knowledge"),
                            ("cs", "Computer Science"),
                        ],
                        max_length=50,
                    ),
                ),
                ("question_text", models.TextField()),
                ("options", models.JSONField()),
                ("correct_option", models.CharField(max_length=1)),
                ("solution", models.TextField()),
            ],
        ),
    ]
