# Generated by Django 5.2 on 2025-04-12 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_clashmatch_clashquestion"),
    ]

    operations = [
        migrations.AddField(
            model_name="clashmatch",
            name="player1_score",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="clashmatch",
            name="player2_score",
            field=models.IntegerField(default=0),
        ),
    ]
