# Generated by Django 5.2 on 2025-04-12 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_clashmatch_player1_score_clashmatch_player2_score"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("description", models.TextField()),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
