# Generated by Django 5.2 on 2025-04-12 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_contact"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="dob",
        ),
    ]
